/**
 * Unit tests for the IIIF region helpers added by plan 020
 * (src/utils/iiif.ts + src/utils/overlay-compositor.ts).
 *
 * All pure functions except readImageDimensions, which is exercised against
 * a tiny JPEG generated by sharp itself — no network, no committed DB.
 *
 * Run with: npm run test:iiif-region
 */

import sharp from 'sharp';
import {
  IIIF_REGION_RE,
  parsePctRegion,
  parseCropPixelsRegion,
  cropPixelsToIiifPixels,
  checkRegionBounds,
  infoJsonUrlFromImageUrl,
  computeEffectiveSize,
  buildIiifRegionUrl,
} from '../src/utils/iiif.js';
import {
  projectToFullImage,
  regionToPixels,
  computeVerificationRegion,
  computeDeliveryState,
} from '../src/utils/iiif.js';
import { readImageDimensions } from '../src/utils/overlay-compositor.js';
import { check, finish } from './test-utils.js';

// ---------------------------------------------------------------------------
// 1. IIIF_REGION_RE
// ---------------------------------------------------------------------------

console.log('1. IIIF_REGION_RE');

const acceptedRegions = [
  'full',
  'square',
  '1473,1041,589,416',
  'pct:31.2,18.4,22.0,6.1',
  'crop_pixels:1,2,3,4',
];
for (const region of acceptedRegions) {
  check(IIIF_REGION_RE.test(region), `accepts '${region}'`);
}

const rejectedRegions = ['pct:1,2,3', 'pct:a,b,c,d', '-5,0,10,10', ''];
for (const region of rejectedRegions) {
  check(!IIIF_REGION_RE.test(region), `rejects '${region}'`);
}

// ---------------------------------------------------------------------------
// 2. parsePctRegion / parseCropPixelsRegion / cropPixelsToIiifPixels
// ---------------------------------------------------------------------------

console.log('2. parsePctRegion / parseCropPixelsRegion / cropPixelsToIiifPixels');

{
  const p = parsePctRegion('pct:31.2,18.4,22.0,6.1');
  check(!!p && p[0] === 31.2 && p[1] === 18.4 && p[2] === 22.0 && p[3] === 6.1, 'parsePctRegion round-trips');
  check(parsePctRegion('full') === null, 'parsePctRegion(full) is null');
  check(parsePctRegion('1,2,3,4') === null, 'parsePctRegion(plain pixels) is null');
}

{
  const p = parseCropPixelsRegion('crop_pixels:1,2,3,4');
  check(!!p && p[0] === 1 && p[1] === 2 && p[2] === 3 && p[3] === 4, 'parseCropPixelsRegion round-trips');
  check(parseCropPixelsRegion('1,2,3,4') === null, 'parseCropPixelsRegion(plain pixels) is null');
  check(parseCropPixelsRegion('pct:1,2,3,4') === null, 'parseCropPixelsRegion(pct) is null');
}

{
  check(cropPixelsToIiifPixels('crop_pixels:1,2,3,4') === '1,2,3,4', 'cropPixelsToIiifPixels strips the prefix');
  check(cropPixelsToIiifPixels('1,2,3,4') === null, 'cropPixelsToIiifPixels(plain pixels) is null');
}

// ---------------------------------------------------------------------------
// 3. checkRegionBounds
// ---------------------------------------------------------------------------

console.log('3. checkRegionBounds');

// full/square always in-bounds
check(checkRegionBounds('full') === null, 'full is always in-bounds');
check(checkRegionBounds('square', 100, 100) === null, 'square is always in-bounds');

// pct in-bounds
check(checkRegionBounds('pct:0,0,100,100') === null, 'pct:0,0,100,100 in-bounds');
check(checkRegionBounds('pct:0,0,100.005,100') === null, 'pct:0,0,100.005,100 within the 100.01 epsilon');

// pct violations
{
  const oob = checkRegionBounds('pct:95,95,10,10');
  check(oob !== null, 'pct:95,95,10,10 flagged out-of-bounds');
  check(oob?.clampedTo === 'pct:95,95,5,5', `pct:95,95,10,10 clamps to pct:95,95,5,5 (got: ${oob?.clampedTo})`);
  check(oob?.requested === 'pct:95,95,10,10', 'requested echoes the exact input');
}
{
  // NB: a literal negative x (e.g. "pct:-5,0,10,10") can never reach this
  // branch — parsePctRegion's [0-9.]+ capture (matching the rijksmuseum
  // source it ports) rejects the '-' sign at the IIIF_REGION_RE/parse layer
  // before checkRegionBounds ever sees it. x>100 exercises the same
  // "outside 0-100" issue branch via a reachable input instead.
  const oob = checkRegionBounds('pct:150,0,10,10');
  check(oob !== null, 'x > 100 flagged out-of-bounds');
  check(oob?.issue.includes('outside 0–100'), 'x > 100 issue mentions the valid range');
  check(oob?.clampedTo === 'pct:100,0,0,10', `x > 100 clamps to pct:100,0,0,10 (got: ${oob?.clampedTo})`);
}
{
  const oob = checkRegionBounds('pct:10,10,0,10');
  check(oob !== null, 'zero w flagged out-of-bounds');
  check(oob?.issue.includes('w=0 must be > 0'), 'zero w issue message');
}

// px with dims
{
  const oob = checkRegionBounds('5000,4000,2000,1000', 5892, 4167);
  check(oob !== null, 'px region exceeding native dims flagged out-of-bounds');
  check(oob?.clampedTo === '5000,4000,892,167', `px region clamps to 5000,4000,892,167 (got: ${oob?.clampedTo})`);
}

// px without dims — only w>0/h>0 checked
check(checkRegionBounds('0,0,10,10') === null, 'px region without native dims: no issue when w,h > 0');
{
  const oob = checkRegionBounds('0,0,0,10');
  check(oob !== null, 'px region without native dims: w=0 still flagged');
  check(oob?.validRange.includes('dimensions unknown'), 'validRange notes dimensions are unknown');
}

// ---------------------------------------------------------------------------
// 4. computeEffectiveSize
// ---------------------------------------------------------------------------

console.log('4. computeEffectiveSize');

{
  // pct 10% of 5892 → floor(589.2) - 3 = 586
  const s = computeEffectiveSize('pct:25,25,10,10', 1568, 5892, 4167);
  check(s === 586, `pct region clamps 1568 -> 586 (got: ${s})`);
}
{
  // px region uses the raw width (589), no -3 rounding margin
  const s = computeEffectiveSize('1473,1041,589,416', 1568, 5892, 4167);
  check(s === 589, `px region clamps 1568 -> 589 (got: ${s})`);
}
{
  const s = computeEffectiveSize('full', 1568, 5892, 4167);
  check(s === 1568, `full region keeps size <= native width (got: ${s})`);
}
{
  const s = computeEffectiveSize('pct:25,25,10,10', 1568);
  check(s === 1568, `unknown dims leave size unchanged (got: ${s})`);
}
{
  const s = computeEffectiveSize('square', 1568, 5892, 4167);
  check(s === 1568, `square region clamps to min(imgW,imgH)=4167, size stays under it (got: ${s})`);
}

// ---------------------------------------------------------------------------
// 5. readImageDimensions (sharp round-trip — also proves the native prebuild
//    installed correctly on this machine)
// ---------------------------------------------------------------------------

console.log('5. readImageDimensions (sharp round-trip)');

{
  const jpeg = await sharp({
    create: { width: 10, height: 8, channels: 3, background: '#fff' },
  })
    .jpeg()
    .toBuffer();
  const dims = await readImageDimensions(jpeg);
  check(dims.width === 10 && dims.height === 8, `readImageDimensions reads {10,8} (got: ${JSON.stringify(dims)})`);
}

// ---------------------------------------------------------------------------
// 6. buildIiifRegionUrl
// ---------------------------------------------------------------------------

console.log('6. buildIiifRegionUrl');

const baseImageUrl = 'https://service.archief.nl/iip/aa/bb/x.jp2/full/max/0/default.jpg';

{
  const url = buildIiifRegionUrl(baseImageUrl, 'pct:25,25,10,10', 400, 0, 'default');
  check(
    url === 'https://service.archief.nl/iip/aa/bb/x.jp2/pct:25,25,10,10/400,/0/default.jpg',
    `builds the region URL (got: ${url})`,
  );
}
{
  const url = buildIiifRegionUrl(baseImageUrl, 'pct:25,25,10,10', 400, 90, 'gray');
  check(
    url === 'https://service.archief.nl/iip/aa/bb/x.jp2/pct:25,25,10,10/400,/90/gray.jpg',
    `builds the region URL with rotation + quality (got: ${url})`,
  );
}
{
  const infoUrl = 'https://service.archief.nl/iip/aa/bb/x.jp2/info.json';
  check(buildIiifRegionUrl(infoUrl, 'full', 400, 0, 'default') === null, 'non-matching URL shape returns null');
}

// ---------------------------------------------------------------------------
// 7. infoJsonUrlFromImageUrl
// ---------------------------------------------------------------------------

console.log('7. infoJsonUrlFromImageUrl');

{
  const infoUrl = infoJsonUrlFromImageUrl(baseImageUrl);
  check(infoUrl === 'https://service.archief.nl/iip/aa/bb/x.jp2/info.json', `derives info.json URL (got: ${infoUrl})`);
}
{
  check(infoJsonUrlFromImageUrl('https://service.archief.nl/iip/aa/bb/x.jp2/info.json') === null, 'already-info.json URL returns null');
  check(infoJsonUrlFromImageUrl('not-a-url') === null, 'unrelated string returns null');
}

// ---------------------------------------------------------------------------
// 8. projectToFullImage (reverse-channel geometry, plan 021)
// ---------------------------------------------------------------------------

console.log('8. projectToFullImage');

{
  // A crop-local pct box within a full-image pct crop → full-image pct.
  // relativeTo = pct:20,20,40,40; local = pct:50,50,10,10 →
  //   fx = 20 + 0.5*40 = 40; fy = 20 + 0.5*40 = 40; fw = 0.1*40 = 4; fh = 4
  const p = projectToFullImage('pct:50,50,10,10', 'pct:20,20,40,40');
  check(p === 'pct:40,40,4,4', `crop-local pct projects to pct:40,40,4,4 (got: ${p})`);
}
{
  // crop_pixels with localSize: 100px within a 200px-wide crop = 50% →
  //   relativeTo pct:0,0,50,50 → fx = 0 + 0.5*50 = 25; fw = 0.5*50 = 25
  const p = projectToFullImage('crop_pixels:100,0,100,80', 'pct:0,0,50,50', { width: 200, height: 160 });
  check(p === 'pct:25,0,25,25', `crop_pixels with localSize projects (got: ${p})`);
}
{
  check(projectToFullImage('crop_pixels:1,2,3,4', 'pct:0,0,50,50') === null, 'crop_pixels without localSize is null');
  check(projectToFullImage('pct:1,2,3,4', 'full') === null, 'non-pct relativeTo is null');
}

// ---------------------------------------------------------------------------
// 9. regionToPixels
// ---------------------------------------------------------------------------

console.log('9. regionToPixels');

{
  const px = regionToPixels('pct:25,25,10,10', 1000, 800);
  check(px === '250,200,100,80', `pct:25,25,10,10 on 1000x800 → 250,200,100,80 (got: ${px})`);
  check(regionToPixels('full', 1000, 800) === undefined, 'regionToPixels(full) is undefined');
  check(regionToPixels('100,100,50,50', 1000, 800) === undefined, 'regionToPixels(plain px) is undefined');
}

// ---------------------------------------------------------------------------
// 10. computeVerificationRegion
// ---------------------------------------------------------------------------

console.log('10. computeVerificationRegion');

{
  // Small overlay (2%) → expands to the 12% floor, centred.
  const v = computeVerificationRegion('pct:40,40,2,2', 5892, 4167);
  check(v === 'pct:35,35,12,12', `small overlay expands to a 12% box centred (got: ${v})`);
}
{
  // Overlay near the edge → shift-clamped to stay inside 0-100.
  const v = computeVerificationRegion('pct:96,96,2,2', 5892, 4167);
  check(v === 'pct:88,88,12,12', `edge overlay shift-clamped into 0-100 (got: ${v})`);
}
{
  check(computeVerificationRegion('full', 5892, 4167) === undefined, 'full → undefined');
  check(computeVerificationRegion('square', 5892, 4167) === undefined, 'square → undefined');
  check(computeVerificationRegion('pct:40,40,2,2') === undefined, 'missing dims → undefined');
}

// ---------------------------------------------------------------------------
// 11. computeDeliveryState
// ---------------------------------------------------------------------------

console.log('11. computeDeliveryState');

{
  const now = 1_000_000;
  check(computeDeliveryState(undefined, now) === 'no_live_viewer_seen', 'never polled → no_live_viewer_seen');
  check(computeDeliveryState(now - 3000, now) === 'delivered_recently', '3s ago → delivered_recently');
  check(computeDeliveryState(now - 10000, now) === 'queued_waiting_for_viewer', '10s ago → queued_waiting_for_viewer');
}

finish('IIIF region tests');
